manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/drorchen
  projects:
    - name: zmk
      remote: drorchen
      revision: mouse-pim447
      import: app/west.yml
  self:
    path: config
