manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ALpotato
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: alpotato-ptdevice
      import: app/west.yml
  self:
    path: config
