manifest:
  remotes:
    - name: ALpotato
      url-base: https://github.com/ALpotato
  projects:
    - name: ufan-zmk
      remote: ALpotato
      revision: alpotato-ptdevice
      import: app/west.yml
  self:
    path: config
