manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/1770438260
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: cirque-trackpad
      import: app/west.yml
  self:
    path: config
