manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/crides
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: fusion-led-c-config
      import: app/west.yml
  self:
    path: config
