manifest:
  remotes:
    - name: jgreel
      url-base: https://github.com/ufan
  projects:
    - name: zmk
      remote: jgreel
      revision: blade
      import: app/west.yml
  self:
    path: config
